CREATE TYPE programming_language AS ENUM ('Python', 'Node.js', 'React.js', 'Typescript', 'JavaScript');
CREATE TYPE status AS ENUM ('Pending', 'In-Progress', 'Submitted');
-- enum is good, if we want to add any values for the column it will be easy.
CREATE TABLE ASSESSMENTS (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4 (),
    NAME TEXT NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    IS_ARCHIVED BOOLEAN NOT NULL,
    REPO_LINK TEXT,
    HIDDEN_TEST_CASES_LINK TEXT,
    LANGUAGE programming_language,
    DESCRIPTION TEXT NOT NULL,
    META_DATA JSONB
);

CREATE TABLE CANDIDATES (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4 (),
    NAME TEXT NOT NULL,
    EMAIL TEXT NOT NULL UNIQUE,
    GITHUB_USERNAME TEXT NOT NULL UNIQUE,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    META_DATA JSONB
);

CREATE TABLE CANDIDATE_ASSESSMENT (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4 (),
    CANDIDATE_ID uuid REFERENCES CANDIDATES (ID), -- FOREIGN KEY 
    ASSESSMENT_TEMPLATES_ID uuid REFERENCES ASSESSMENT_TEMPLATES (ID), -- FOREIGN KEY
    INVITED_ON TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    STARTED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    SUBMITTED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    SHA TEXT,
    PR_NAME TEXT,
    CANDIDATE_REPO_LINK TEXT,
    STATUS status,
    TOTAL_TESTCASES INT NOT NULL,
    PASSED_TESTCASES INT NOT NULL,
    FAILED_TESTCASES INT NOT NULL,
    RESULTS JSONB -- result-score, result-summary
);   



