CREATE TYPE programming_language AS ENUM ('Python', 'Node.js', 'React.js', 'Typescript', 'JavaScript');
CREATE TYPE status AS ENUM ('Pending', 'In-Progress', 'Submitted');

CREATE TABLE ASSESSMENT_TEMPLATES (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4 (),
    NAME TEXT NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    IS_ARCHIVED BOOLEAN NOT NULL,
    REPO_LINK TEXT,
    LANGUAGE programming_language,
    DESCRIPTION TEXT NOT NULL,
    META_DATA JSONB
);

CREATE TABLE CANDIDATES (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4 (),
    NAME TEXT NOT NULL,
    EMAIL TEXT NOT NULL UNIQUE,
    GITHUB_USERNAME TEXT NOT NULL UNIQUE,
    YEAR_OF_EXPERIENCE INT,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    META_DATA JSONB
);

CREATE TABLE CANDIDATE_ASSESSMENT (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4 (),
    CANDIDATE_ID uuid REFERENCES CANDIDATES (ID), -- FOREIGN KEY 
    ASSESSMENT_TEMPLATES_ID uuid REFERENCES ASSESSMENT_TEMPLATES (ID), -- FOREIGN KEY
    ASSESSMENT_SENT_TIME WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    STARTED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    SUBMITTED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    STATUS status,
    TOTAL_TESTCASES INT NOT NULL,
    PASSED_TESTCASES INT NOT NULL,
    FAILED_TESTCASES INT NOT NULL,
    ACCEPTANCE DECIMAL GENERATED ALWAYS AS (
        (PASSED_TESTCASES - TOTAL_TESTCASES) / 100.0
    ) STORED,
    TIME_TAKEN DECIMAL(6, 2) GENERATED ALWAYS AS (
        EXTRACT(EPOCH FROM (SUBMITTED_AT - STARTED_AT)) / 3600.0
    ) STORED,
    META_DATA JSONB
);   



